- name: Create {{ env }} cfssl SVM
  na_ontap_svm:
    state: present
    name: "{{ env }}_cfssl"
    aggr_list: "{{ cfssl_aggregate_list }}"
    allowed_protocols:
    - iscsi
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create iscsi service on {{ env }} cfssl SVM
  na_ontap_iscsi:
    state: present
    service_state: started
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create route for {{ env }} cfssl outgoing traffic
  na_ontap_net_routes:
    state: present
    destination: 0.0.0.0/0
    gateway: "{{ cfssl_network_gateway }}"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create {{ env }} cfssl vserver data lif on controller {{ node_1 }}
  na_ontap_interface:
    state: present
    interface_name: "{{ env }}_cfssl_data_lif_1"
    home_port: "{{ vlan_port }}"
    home_node: "{{ node_1 }}"
    role: data
    protocols: iscsi
    admin_status: up
    address: "{{ cfssl_data_lif_1_address }}"
    netmask: "{{ cfssl_lif_netmask }}"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create {{ env }} cfssl vserver data lif on controller {{ node_2 }}
  na_ontap_interface:
    state: present
    interface_name: "{{ env }}_cfssl_data_lif_2"
    home_port: "{{ vlan_port }}"
    home_node: "{{ node_2 }}"
    role: data
    protocols: iscsi
    admin_status: up
    address: "{{ cfssl_data_lif_2_address }}"
    netmask: "{{ cfssl_lif_netmask }}"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create iSCSI Igroup for {{ env }} cfssl
  na_ontap_igroup:
    state: present
    name: "{{ env }}CfsslIgroup"
    initiator_group_type: iscsi
    ostype: linux
    initiators: "{{ cfssl_igroup_initiator }}"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create {{ env }} cfssl snapshot policy
  na_ontap_snapshot_policy:
    state: present
    name: "{{ env }}_cfssl"
    schedule: daily
    count: 3
    enabled: True
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create {{ env }} cfssl volume
  na_ontap_volume:
    state: present
    name: "{{ env }}_cfssl_vol"
    is_infinite: False
    aggregate_name: "{{ cfssl_volume_aggregate }}"
    size: 2200
    size_unit: mb
    tiering_policy: auto
    policy: default
    encrypt: yes
    wait_for_completion: True
    comment: "ansible created {{ env }} cfssl volume"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create {{ env }} cfssl LUN
  na_ontap_lun:
    state: present
    name: "{{ env }}_cfssl_lun"
    flexvol_name: "{{ env }}_cfssl_vol"
    size: 2
    size_unit: gb
    ostype: linux
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create {{ env }} cfssl LUN mapping
  na_ontap_lun_map:
    state: present
    initiator_group_name: "{{ env }}CfsslIgroup"
    path: "/vol/dev_cfssl_vol/dev_cfssl_lun"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# https://github.com/ansible-collections/netapp/blob/master/ansible_collections/netapp/ontap/plugins/modules/na_ontap_iscsi_security.py
- name: Create {{ env }} cfssl iSCSI initiator security policy
  netapp.ontap.na_ontap_iscsi_security:
    state: present
    initiator: "{{ cfssl_igroup_initiator }}"
    inbound_username: "{{ env }}_cfssl"
    inbound_password: "{{ cfssl_chap_password }}"
    auth_type: chap
    address_ranges: "{{ cfssl_initiator_ip }}"
    vserver: "{{ env }}_cfssl"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    validate_certs: no # collection errors when it cannot verify the server cert
