# This will ensure that we have configured a failover group and policy for our
# cluster management lif, so that it will only migrate to controller's e0M ports
# which are connected to the management network.
# Unfortunately, ansible modules do not seem to offer a way to create failover
# groups, so we need to run the following command manual:
# system::> network interface failover-groups create -vserver system -failover-group mgmt_failover -targets system-01:e0M,system-02:e0M

# Next we need to configure the cluster management lif to use the above failover
# group. Equivalent netapp cli command:
# system::> network interface modify -vserver system -lif cluster_mgmt_lif -failover-policy system-defined -failover-group mgmt_failover
- name: Ensure Cluster Management interface failover group
  netapp.ontap.na_ontap_interface:
    state: present
    interface_name: cluster_mgmt_lif
    home_port: e0M
    home_node: system-01
    role: cluster-mgmt
    admin_status: up
    failover_policy: system-defined
    failover_group: mgmt_failover
    firewall_policy: mgmt
    vserver: system
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  tags: cluster

# We saw an incident where cluster management interfaces held different IP addresses than the ones reserved in management network DHCP.
# Let's put the ones configured in DHCP down here to make sure we can match them for future operations
- name: Ensure system-01_mgmt interface address
  netapp.ontap.na_ontap_interface:
    state: present
    interface_name: system-01_mgmt
    address: 10.91.5.92
    netmask: 255.255.255.0
    vserver: system
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  tags: cluster

- name: Ensure system-02_mgmt interface address
  netapp.ontap.na_ontap_interface:
    state: present
    interface_name: system-02_mgmt
    address: 10.91.5.98
    netmask: 255.255.255.0
    vserver: system
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  tags: cluster

# New management interfaces for ld7 network
- name: Ensure system-01_mgmt_ld7 interface address
  netapp.ontap.na_ontap_interface:
    state: present
    admin_status: up
    interface_name: system-01_mgmt_ld7
    address: 10.71.5.110
    netmask: 255.255.255.0
    broadcast_domain: Default
    ipspace: Default
    home_port: e0M
    home_node: system-01
    failover_policy: local-only
    firewall_policy: mgmt
    role: node-mgmt
    vserver: system
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  tags: cluster

- name: Ensure system-02_mgmt_ld7 interface address
  netapp.ontap.na_ontap_interface:
    state: present
    admin_status: up
    interface_name: system-02_mgmt_ld7
    address: 10.71.5.112
    netmask: 255.255.255.0
    broadcast_domain: Default
    ipspace: Default
    home_port: e0M
    home_node: system-02
    failover_policy: local-only
    firewall_policy: mgmt
    role: node-mgmt
    vserver: system
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  tags: cluster

- name: Cluster Management failover interface
  netapp.ontap.na_ontap_interface:
    state: present
    admin_status: up
    interface_name: cluster_mgmt_lif_ld7
    address: 10.71.5.15
    netmask: 255.255.255.0
    broadcast_domain: Default
    ipspace: Default
    home_port: e0M
    home_node: system-01
    service_policy: default-management
    failover_policy: system-defined
    failover_group: mgmt_failover
    firewall_policy: mgmt
    vserver: system
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  tags: cluster

# Ensure lldb mode is enabled for both controllers
- name: Enable lldb on nodes
  netapp.ontap.na_ontap_rest_cli:
    validate_certs: false # Self signed NetApp certificate
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    command: options
    verb: PATCH
    params:
      option_name: lldp.enable
    body:
      option_value: "on"
  tags: cluster
