# Create ipscpaces for each env
- name: Create {{ env }} dedicated ipspace
  na_ontap_ipspace:
    state: present
    name: "{{ ipspace_name }}"
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Create a broadcast domain for each env and assign all the ports of the environment to it
- name: Create {{ env }} broadcast domain
  na_ontap_broadcast_domain:
    state: present
    name: "{{ env }}_domain"
    mtu: "{{ default_mtu }}"
    ipspace: "{{ ipspace_name }}"
    ports:
      - "{{ node_1 }}:{{ vlan_port_1 }}"
      - "{{ node_1 }}:{{ vlan_port_2 }}"
      - "{{ node_2 }}:{{ vlan_port_1 }}"
      - "{{ node_2 }}:{{ vlan_port_2 }}"
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Assign a port on each node to each env vlan
- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_1 }} for {{ vlan_parent_interface_1 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_1 }}"
    parent_interface: "{{ vlan_parent_interface_1 }}"
    broadcast_domain: "{{ env }}_domain"
    ipspace: "{{ ipspace_name }}"
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_2 }} for {{ vlan_parent_interface_1 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_2 }}"
    parent_interface: "{{ vlan_parent_interface_1 }}"
    broadcast_domain: "{{ env }}_domain"
    ipspace: "{{ ipspace_name }}"
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_1 }} for {{ vlan_parent_interface_2 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_1 }}"
    parent_interface: "{{ vlan_parent_interface_2 }}"
    broadcast_domain: "{{ env }}_domain"
    ipspace: "{{ ipspace_name }}"
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_2 }} for {{ vlan_parent_interface_2 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_2 }}"
    parent_interface: "{{ vlan_parent_interface_2 }}"
    broadcast_domain: "{{ env }}_domain"
    ipspace: "{{ ipspace_name }}"
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Use jumbo frames in the default broadcast domain
- name: Set mtu {{ default_mtu }} for Default broadcast domain
  na_ontap_broadcast_domain:
    state: present
    name: Default
    mtu: "{{ default_mtu }}"
    ipspace: Default
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Enable autosupport for controllers
# https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-sag%2FGUID-91C43742-E563-442E-8161-17D5C5DA8C19.html
- name: Ensure AutoSupport is enabled and configured for technical support to receive messages on {{ node_1 }}
  na_ontap_autosupport:
    state: present
    node_name: "{{ node_1 }}"
    transport: https
    support: True
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Ensure AutoSupport is enabled and configured for technical support to receive messages on {{ node_2 }}
  na_ontap_autosupport:
    state: present
    node_name: "{{ node_2 }}"
    transport: https
    support: True
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Autosupport traffic is sent using the node mgmt lifs and uses node svm dns
# settings to resolve. For us the management/node svm is system so we need to
# configure it to resolve netapp addresses.
# https://community.netapp.com/t5/ONTAP-Discussions/Configuring-Autosupport-Resolve-DNS/m-p/116019/highlight/true#M24743
- name: Configure dns on system vserver to be able to resolve autosupport traffic
  na_ontap_dns:
    state: present
    vserver: system
    domains: netapp.com
    nameservers: 1.1.1.1,1.0.0.1
    use_rest: always
    validate_certs: false
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
