# Assign a port on each node to each env vlan
- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_1 }} for {{ vlan_parent_interface_1 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_1 }}"
    parent_interface: "{{ vlan_parent_interface_1 }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_2 }} for {{ vlan_parent_interface_1 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_2 }}"
    parent_interface: "{{ vlan_parent_interface_1 }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_1 }} for {{ vlan_parent_interface_2 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_1 }}"
    parent_interface: "{{ vlan_parent_interface_2 }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: create {{ env }} VLAN {{ vlan_id }} on {{ node_2 }} for {{ vlan_parent_interface_2 }}
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ vlan_id }}"
    node: "{{ node_2 }}"
    parent_interface: "{{ vlan_parent_interface_2 }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Create ipscpaces for each env
- name: Create {{ env }} dedicated ipspace
  na_ontap_ipspace:
    state: present
    name: "{{ ipspace_name }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Create a broadcast domain for each env and assign all the ports of the environment to it
- name: Create {{ env }} broadcast domain
  na_ontap_broadcast_domain:
    state: present
    name: "{{ env }}_domain"
    mtu: "{{ default_mtu }}"
    ipspace: "{{ ipspace_name }}"
    ports:
      - "{{ node_1 }}:{{ vlan_port_1 }}"
      - "{{ node_1 }}:{{ vlan_port_2 }}"
      - "{{ node_2 }}:{{ vlan_port_1 }}"
      - "{{ node_2 }}:{{ vlan_port_2 }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

# Use jumbo frames in the default broadcast domain
- name: Set mtu {{ default_mtu }} for Default broadcast domain
  na_ontap_broadcast_domain:
    state: present
    name: Default
    mtu: "{{ default_mtu }}"
    ipspace: Default
    hostname: "{{ inventory_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
