- name: Ensure Cluster Management Interface is properly set
  include_tasks: cluster-mgmt.yaml
  tags: cluster

- name: Create core network connectivity
  include_tasks: core.yaml

- name: Create cfssl SVM and volume
  include_tasks: cfssl.yaml

- name: Create kube SVM and trident user
  include_tasks: kube.yaml

- name: Create nfs SVM and volumes
  include_tasks: nfs.yaml

- name: Create metrics exporter user
  include_tasks: metrics-exporter.yaml
