- name: Create core network connectivity
  include: core.yaml

- name: Create cfssl SVM and volume
  include: cfssl.yaml

- name: Create kube SVM and trident user
  include: kube.yaml

- name: Create nfs SVM and volumes
  include: nfs.yaml

- name: Create metrics exporter user
  include: metrics-exporter.yaml
