- hosts: exp-cumulus
  user: cumulus
  connection: ssh
  roles:
    - cumulus-common
    - cumulus-exp
  vars_files:
    - inventories/group_vars/cumulus-common
    - inventories/group_vars/vault
    - inventories/group_vars/hosts-exp
  become: yes
