- hosts: cumulus-exp
  user: cumulus
  connection: ssh
  roles:
    - cumulus
  vars:
    - network_templates: exp
    - frr_templates: exp
  vars_files:
    - inventories/group_vars/cumulus-exp
    - inventories/group_vars/vault
    - inventories/group_vars/hosts-exp
  become: yes
