- hosts: netapp
  collections:
    - netapp.ontap
  roles:
    - netapp
  vars_files:
    - inventories/group_vars/netapp-prod
    - inventories/group_vars/secrets/netapp-common
    - inventories/group_vars/secrets/netapp-prod
  vars:
    ansible_connection: local
