- name: Copy frr configuration
  template:
    src:  frr.conf.tmpl
    dest: "/etc/frr/frr.conf"
  notify:
    - restart frr
  tags: frr

- name: Enable BGP and PBR
  template:
    src:  files/daemons
    dest: "/etc/frr/daemons"
  notify:
    - restart frr
  tags: frr

- name: Copy network interfaces configuration
  template:
    src: network-interfaces.tmpl
    dest: "/etc/network/interfaces"
  notify:
    - reload network interfaces
  tags: network
