- name: copy authorized_keys file
  copy:
    src: "files/authorized_keys"
    dest: "/home/cumulus/.ssh/authorized_keys"
  tags: ssh_authorized_keys

- name: copy 10ssh.rules
  copy:
    src: "files/10ssh.rules"
    dest: "/etc/cumulus/acl/policy.d/10ssh.rules"
  notify:
    - "install ACL rules"
  tags: ssh_rules

- name: Copy frr configuration
  template:
    src:  frr.conf.tmpl
    dest: "/etc/frr/frr.conf"
  notify:
    - restart frr
  tags: frr
