- name: restart dhcp
  service:
    name: "dhcp-{{ dhcp_role_name }}"
    state: restarted
  become: yes

- name: restart atftp
  service:
    name: "atftp-{{ dhcp_role_name }}"
    state: restarted
  become: yes

- name: daemon-reload
  systemd:
    daemon_reload: yes
