- name: Make sure dhcpd is installed
  apt:
    name: isc-dhcp-server
    state: present
    update_cache: yes
  tags: dhcp

- name: Create /etc/dhcp-{{ dhcp_role_name }}
  file:
    path: "/etc/dhcp-{{ dhcp_role_name }}"
    state: directory
  tags: dhcp

- name: Copy dhcp configuration
  template:
    src:  dhcp.conf.tmpl
    dest: "/etc/dhcp-{{ dhcp_role_name }}/dhcp.conf"
  notify:
    - restart dhcp
  tags: dhcp

- name: Copy dhcp system unit file
  template:
    src:  dhcp.service.tmpl
    dest: "/etc/systemd/system/dhcp-{{ dhcp_role_name }}.service"
  notify:
    - daemon-reload
    - restart dhcp
  tags: dhcp

- name: Make sure dhcp is running and enabled
  service:
    name: "dhcp-{{ dhcp_role_name }}"
    state: started
    enabled: yes
  tags: dhcp

- name: Make sure atftpd is installed
  apt:
    name: atftpd
    state: present
    update_cache: yes
  tags: dhcp

- name: Create /etc/tftpboot-{{ dhcp_role_name }}
  file:
    path: /etc/tftpboot-{{ dhcp_role_name }}
    state: directory
  tags: dhcp

# Ideally we want to fetch this directly on the target host via get_url from
# our bucket roles/dhcp/files/ipxe.pxe. The problem here is that we need to
# specify a vrf on cumulus to be able to talk to the internet and this is not
# available via the ansible command. Thus we include ipxe.pxe in the repo and
# use a simple copy to put it in place.
- name: Copy ipxe file into cumulus
  copy:
    src: roles/dhcp/files/ipxe.pxe
    dest: "/etc/tftpboot-{{ dhcp_role_name }}/ipxe.pxe"
    mode: 0644
  tags: dhcp

# Same as above for ipxe.efi, needed by m510 cartridges
- name: Copy ipxe file into cumulus
  copy:
    src: roles/dhcp/files/ipxe.efi
    dest: "/etc/tftpboot-{{ dhcp_role_name }}/ipxe.efi"
    mode: 0644
  tags: dhcp

- name: Copy atftp system unit file
  template:
    src:  atftp.service.tmpl
    dest: "/etc/systemd/system/atftp-{{ dhcp_role_name }}.service"
  notify:
    - daemon-reload
    - restart atftp
  tags: dhcp

- name: Make sure atftp is running and enabled
  service:
    name: "atftp-{{ dhcp_role_name }}"
    state: started
    enabled: yes
  tags: dhcp
