- name: Make sure docker is installed
  apt:
    name: docker
    state: present
    update_cache: yes
  become: yes
  when:
    - ansible_facts['distribution'] == "Debian"

- name: Create /etc/dnsmasq
  file:
    path: /etc/dnsmasq
    state: directory
  tags: dhcp

- name: Create /etc/dnsmasq/tftpboot
  file:
    path: /etc/dnsmasq/tftpboot
    state: directory
  tags: dhcp

- name: Create /etc/dnsmasq/tftpboot/pxelinux.cfg
  file:
    path: /etc/dnsmasq/tftpboot/pxelinux.cfg
    state: directory
  tags: dhcp

- name: Copy dhcp configuration
  template:
    src:  dnsmasq.conf.tmpl
    dest: /etc/dnsmasq/dnsmasq.conf
  notify:
    - restart dnsmasq-dhcp
  tags: dhcp

- name: Copy pxe linux default configuration
  template:
    src:  pxelinux.cfg.default.tmpl
    dest: /etc/dnsmasq/tftpboot/pxelinux.cfg/default
  notify:
    - restart dnsmasq-dhcp
  tags: dhcp

- name: Download undionly.kpxe
  get_url:
    url: http://boot.salstar.sk/ipxe/undionly.kpxe
    dest: /etc/dnsmasq/tftpboot/undionly.kpxe
    mode: 0644
    checksum: sha256:5666c3359b33278a5f75562a89239a861987d595bf351aff40cbcc1e1830a322
  notify:
    - restart dnsmasq-dhcp
  tags: dhcp

- name: Download ipxe.efi
  get_url:
    url: http://boot.salstar.sk/ipxe/ipxe.efi
    dest: /etc/dnsmasq/tftpboot/ipxe.efi
    mode: 0644
    checksum: sha256:2b2c830214ac4202adf05c625ee71e2a20fa2450e7ba52e0d3abb2f7ff1049e2
  notify:
    - restart dnsmasq-dhcp
  tags: dhcp

- name: Copy dnsmasq-dhcp system unit file
  template:
    src:  dnsmasq-dhcp.service.tmpl
    dest: /etc/systemd/system/dnsmasq-dhcp.service
  become: yes
  notify:
    - daemon-reload
    - restart dnsmasq-dhcp
  tags: dhcp

- name: Make sure dnsmasq-dhcp is running and enabled
  service:
    name: dnsmasq-dhcp
    state: started
    enabled: yes
  become: yes
  tags: dhcp
