- name: Make sure dhcpd is installed
  apt:
    name: dhcpd
    state: present
    update_cache: yes
  become: yes
  when:
    - ansible_facts['distribution'] == "Debian"
  tags: dhcp

- name: Create /etc/dhcp-{{ dhcp_vrf_name }}
  file:
    path: "/etc/dhcp-{{ dhcp_vrf_name }}"
    state: directory
  tags: dhcp

- name: Copy dhcp configuration
  template:
    src:  dhcp.conf.tmpl
    dest: "/etc/dhcp-{{ dhcp_vrf_name }}/dhcp.conf"
  notify:
    - restart dhcp
  tags: dhcp

- name: Copy dhcp system unit file
  template:
    src:  dhcp.service.tmpl
    dest: "/etc/systemd/system/dhcp-{{ dhcp_vrf_name }}.service"
  become: yes
  notify:
    - daemon-reload
    - restart dhcp
  tags: dhcp

- name: Make sure dhcp is running and enabled
  service:
    name: "dhcp-{{ dhcp_vrf_name }}"
    state: started
    enabled: yes
  become: yes
  tags: dhcp

- name: Make sure atftpd is installed
  apt:
    name: atftpd
    state: present
    update_cache: yes
  become: yes
  when:
    - ansible_facts['distribution'] == "Debian"
  tags: dhcp

- name: Create /etc/tftpboot-{{ dhcp_vrf_name }}
  file:
    path: /etc/tftpboot-{{ dhcp_vrf_name }}
    state: directory
  tags: dhcp

- name: Download ipxe.efi
  get_url:
    url: https://storage.googleapis.com/sys-ipxe/ipxe.pxe
    dest: "/etc/tftpboot-{{ dhcp_vrf_name }}/ipxe.pxe"
    checksum: sha256:82c39e589a1b45db3c6cb58bcf14f47a1330778c4c2e61d57156cb9ec575ae87
    mode: 0644
  notify:
    - restart atftp
  tags: dhcp

- name: Copy atftp system unit file
  template:
    src:  atftp.service.tmpl
    dest: "/etc/systemd/system/atftp-{{ dhcp_vrf_name }}.service"
  become: yes
  notify:
    - daemon-reload
    - restart atftp
  tags: dhcp

- name: Make sure atftp is running and enabled
  service:
    name: "atftp-{{ dhcp_vrf_name }}"
    state: started
    enabled: yes
  become: yes
  tags: dhcp
