- name: install ACL rules
  command:
    cmd: "cl-acltool -i"
  become: true

- name: restart frr
  service:
    name: frr.service
    state: restarted
  become: yes

- name: restart node-exporter
  service:
    name: node-exporter.service
    state: restarted
  become: yes

- name: daemon-reload
  systemd:
    daemon_reload: yes
