- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: install ACL rules
  command:
    cmd: "cl-acltool -i"
  become: yes

- name: reload network interfaces
  command:
    cmd: "ifreload -a"
  become: yes

- name: restart frr
  service:
    name: frr.service
    state: restarted
  become: yes

- name: restart node-exporter
  service:
    name: node-exporter.service
    state: restarted
  become: yes

- name: update timezone
  command:
    cmd: "ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime"
  become: yes
