# Kubernetes Vlan
- name: Ensure VLAN {{ kube_vlan_id }} exists
  nxos_vlan:
    vlan_id: "{{ kube_vlan_id }}"
    name: "{{ kube_vlan_name }}"
    state: present
  tags:
  - kubernetes

- name: Ensure VLAN is {{ kube_vlan_id }} is up and active
  nxos_vlan:
    vlan_id: "{{ kube_vlan_id }}"
    name: "{{ kube_vlan_name }}"
    admin_state: up
    vlan_state: active
  tags:
  - kubernetes

- name: Ensure ports are configured for access vlan "{{ kube_vlan_id }}"
  nxos_l2_interface:
    interface: "{{ item }}"
    mode: access
    access_vlan: "{{ kube_vlan_id }}"
  loop: "{{ kube_iport_list }}"
  tags:
  - kubernetes

- name: Ensure ports interfaces are up
  nxos_interface:
    name: "{{ item }}"
    admin_state: up
  loop: "{{ kube_iport_list }}"
  tags:
  - kubernetes

- name: Configure spanning-tree port type to edge for all port interfaces
  nxos_config:
    lines:
      - "spanning-tree port type edge"
    parents:
      - "interface {{ item }}"
  loop: "{{ kube_iport_list }}"
  when: not ansible_check_mode
  tags:
  - kubernetes

- name: Create interface SVI {{ kube_vlan_id }}
  nxos_interface:
    name: "vlan{{ kube_vlan_id }}"
    interface_type: svi
    admin_state: up
    state: present
  tags:
  - kubernetes

- name: Ensure vlan {{kube_vlan_id}} exist on environment's vrf
  nxos_vrf_interface:
    vrf: "{{ env_vrf }}"
    interface: "vlan{{ kube_vlan_id }}"
    state: present
  tags:
  - kubernetes

- name: Set interface IPv4 address for SVI "{{ kube_vlan_id }}"
  nxos_l3_interface:
    name: "vlan{{ kube_vlan_id }}"
    ipv4: "{{ kube_vlan_ip_address}}/{{ kube_vlan_ip_netmask }}"
    state: present
  tags:
  - kubernetes
