- name: Create vrf
  include: vrf.yaml

- name: Create and configure kubernetes vlan
  include: kubernetes-vlan.yaml

- name: Create and configure connectivity to parent switch
  include: parent-sw-connection.yaml

- name: Configure routing rules
  include: routing.yaml

- name: Configure connection with netapp
  include: netapp.yaml
