- name: Make sure ssh and openssh-server are installed
  apt:
    name: "{{ packages }}" 
    state: present
    update_cache: yes
  vars:
    packages:
    - ssh
    - openssh-server
  become: yes
  when:
    - ansible_facts['distribution'] == "Debian"

- name: Copy sshd configuration
  template:
    src:  sshd_config.tmpl 
    dest: /etc/ssh/sshd_config
  become: yes
  notify:
    - restart sshd
  tags: sshd

- name: Make sure sshd is running and enabled
  service:
    name: sshd
    state: started
    enabled: yes
  become: yes
  tags: sshd
